### ISSUE TITLE
Availability via Homebrew

### ISSUE THREAD

**Issue by genebean** [frigus02/kyml#26]
Any chance you'd make this available via Homebrew?

**Comment by frigus02** [comment]
Hi. That sounds like a good idea.

I've not added a package to Homebrew before. Do you know the best way to do that by any chance?

**Comment by genebean** [comment]
Most people create a repo to hold their formulas and setup ci to do the publishing. https://docs.brew.sh/Adding-Software-to-Homebrew has some info that would be helpful. If you wanted to create a repo such as frigus02/homebrew-frigus02 I’d be happy to collaborate on it.

**Comment by frigus02** [comment]
Okay. Creating a tap repository sounds easy enough. As long as there kyml releases aren't too frequent I can even keep that updated manually. I'm going to give that a go.

**Comment by frigus02** [comment]
Alright. This is the easiest I could come up with. Seems to work on my Intel Mac:

https://github.com/frigus02/homebrew-tap/blob/dc158e5cf10d97741f3952f5a81aa7a14b263d04/kyml.rb

```
brew install frigus02/tap/kyml
```

Let me know if this works for you and also if something can be improved 🙂
